import type { HashDriverContract } from '@adonisjs/core/types/hash';
import bcrypt from 'bcryptjs';

/**
 * Hash driver producing and verifying standard modular-crypt bcrypt
 * hashes (`$2a$`, `$2b$`, `$2y$`). AdonisJS's built-in bcrypt driver
 * only understands its own PHC format, which would reject hashes
 * generated by PHP/Laravel — including the staging basic auth
 * password hash already stored in DigitalOcean.
 */
export class BcryptjsHashDriver implements HashDriverContract {
  constructor(private config: { rounds: number }) {}

  isValidHash(value: string): boolean {
    return /^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$/.test(value);
  }

  make(value: string): Promise<string> {
    return bcrypt.hash(value, this.config.rounds);
  }

  async verify(hashedValue: string, plainValue: string): Promise<boolean> {
    if (!this.isValidHash(hashedValue)) {
      return false;
    }

    return bcrypt.compare(plainValue, hashedValue);
  }

  needsReHash(hashedValue: string): boolean {
    return bcrypt.getRounds(hashedValue) !== this.config.rounds;
  }
}
