import app from '@adonisjs/core/services/app';
import hash from '@adonisjs/core/services/hash';
import { test } from '@japa/runner';
import type { StagingBasicAuthConfig } from '#config/staging';

function basicAuthHeader(user: string, password: string): string {
  return `Basic ${Buffer.from(`${user}:${password}`).toString('base64')}`;
}

test.group('Staging basic auth', (group) => {
  group.each.setup(() => {
    const original =
      app.config.get<StagingBasicAuthConfig>('staging.basicAuth');

    return () => app.config.set('staging.basicAuth', original);
  });

  async function enableBasicAuth(): Promise<void> {
    app.config.set('staging.basicAuth', {
      enabled: true,
      user: 'testuser',
      passwordHash: await hash.make('correct-horse'),
    } satisfies StagingBasicAuthConfig);
  }

  test('lets requests through untouched when disabled', async ({ client }) => {
    app.config.set('staging.basicAuth', {
      enabled: false,
      user: '',
      passwordHash: '',
    } satisfies StagingBasicAuthConfig);

    const response = await client.get('/');

    response.assertStatus(200);
    response.assertHeaderMissing('x-robots-tag');
  });

  test('rejects requests without credentials when enabled', async ({
    client,
  }) => {
    await enableBasicAuth();

    const response = await client.get('/');

    response.assertStatus(401);
    response.assertHeader('www-authenticate', 'Basic realm="Staging"');
    response.assertHeader('x-robots-tag', 'noindex');
  });

  test('rejects the wrong password', async ({ client }) => {
    await enableBasicAuth();

    const response = await client
      .get('/')
      .header('Authorization', basicAuthHeader('testuser', 'wrong-password'));

    response.assertStatus(401);
  });

  test('rejects the wrong username', async ({ client }) => {
    await enableBasicAuth();

    const response = await client
      .get('/')
      .header(
        'Authorization',
        basicAuthHeader('someone-else', 'correct-horse'),
      );

    response.assertStatus(401);
  });

  test('accepts the correct username and password checked against the stored hash', async ({
    client,
  }) => {
    await enableBasicAuth();

    const response = await client
      .get('/')
      .header('Authorization', basicAuthHeader('testuser', 'correct-horse'));

    response.assertStatus(200);
    response.assertHeader('x-robots-tag', 'noindex');
  });

  test('accepts a $2y$ bcrypt hash generated by PHP/Laravel', async ({
    client,
  }) => {
    app.config.set('staging.basicAuth', {
      enabled: true,
      user: 'testuser',
      // password_hash('correct-horse', PASSWORD_BCRYPT, ['cost' => 12])
      passwordHash:
        '$2y$12$nFtQQ/EUZZDhBK7y.r6oJOCmeASmy8HO3MZxyumAg3Z0/Xw2kw.Im',
    } satisfies StagingBasicAuthConfig);

    const response = await client
      .get('/')
      .header('Authorization', basicAuthHeader('testuser', 'correct-horse'));

    response.assertStatus(200);
  });

  test('leaves the health check reachable without credentials', async ({
    client,
  }) => {
    await enableBasicAuth();

    const response = await client.get('/up');

    response.assertStatus(200);
  });
});
