import { test } from '@japa/runner';
import { BcryptjsHashDriver } from '#services/bcryptjs_hash_driver';

test.group('BcryptjsHashDriver', () => {
  const driver = new BcryptjsHashDriver({ rounds: 4 });

  test('hashes and verifies a value', async ({ assert }) => {
    const hashed = await driver.make('correct-horse');

    assert.isTrue(driver.isValidHash(hashed));
    assert.isTrue(await driver.verify(hashed, 'correct-horse'));
    assert.isFalse(await driver.verify(hashed, 'wrong-password'));
  });

  test('verifies $2y$ hashes generated by PHP/Laravel', async ({ assert }) => {
    const laravelHash =
      '$2y$12$nFtQQ/EUZZDhBK7y.r6oJOCmeASmy8HO3MZxyumAg3Z0/Xw2kw.Im';

    assert.isTrue(await driver.verify(laravelHash, 'correct-horse'));
    assert.isFalse(await driver.verify(laravelHash, 'wrong-password'));
  });

  test('rejects values that are not bcrypt hashes', async ({ assert }) => {
    assert.isFalse(driver.isValidHash('correct-horse'));
    assert.isFalse(await driver.verify('correct-horse', 'correct-horse'));
  });

  test('flags hashes made with different rounds for rehashing', async ({
    assert,
  }) => {
    const hashed = await driver.make('correct-horse');

    assert.isFalse(driver.needsReHash(hashed));
    assert.isTrue(new BcryptjsHashDriver({ rounds: 5 }).needsReHash(hashed));
  });
});
